#!/bin/bash


#SBATCH -n 24                         # Request X X cores
#SBATCH -p parallel-24
#SBATCH -t 168:00:00                   # The job can take at most X wall-clock hours.
#SBATCH -J Methane_NPT                 # Jobname

##SBATCH --constraint="XeonE51650v2"


lmp=/home/noura/LAMMPS/tests/src_v05

mpi=/usr/local/openmpi-1.8.4-ifort/bin

$mpi/mpirun -np 24 $lmp/lmp_mpi < in.CH4



sleep 2


exit 0

